/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': 'var(--color-on-surface)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface': 'var(--color-surface)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'tertiary': 'var(--color-tertiary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary': 'var(--color-secondary)',
        'outline': 'var(--color-outline)',
        'primary-container': 'var(--color-primary-container)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'background': 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-error-container': 'var(--color-on-error-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-error': 'var(--color-on-error)',
        'surface-dim': 'var(--color-surface-dim)',
        'error': 'var(--color-error)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-container': 'var(--color-surface-container)',
        'error-container': 'var(--color-error-container)',
        'primary': 'var(--color-primary)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-secondary': 'var(--color-on-secondary)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'surface-bright': 'var(--color-surface-bright)',
        'secondary-container': 'var(--color-secondary-container)',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
